apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data--pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pihole-pod
  annotations:
    io.podman.annotations.Network: "homeserver01-network"
  labels:
    app: pihole
spec:
  containers:
  - name: pihole
    image: docker.io/pihole/pihole:latest
    ports:
    - containerPort: 53
      hostPort: 153
      protocol: UDP
    - containerPort: 53
      hostPort: 153
      protocol: TCP
    - containerPort: 80
      hostPort: 180
      protocol: TCP
    env:
    - name: TZ
      value: "UTC"
    - name: WEBPASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-secrets
          key: web-password
    - name: MAXDBDAYS
      value: "30"
    volumeMounts:
    - mountPath: /etc/pihole
      name: data-storage
    - mountPath: /etc/dnsmasq.d
      name: dnsmasq-storage
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: pihole-data-pvc
  - name: dnsmasq-storage
    persistentVolumeClaim:
      claimName: pihole-dnsmasq-pvc