apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pihole-pod
  annotations:
    io.podman.annotations.network: "homeserver01-network"
  labels:
    app: pihole
spec:
  containers:
  - name:  pihole
    image: docker.io/pihole/pihole:latest
    ports:
    - containerPort: 53
      hostPort: 53
      protocol: UDP
    - containerPort: 53
      hostPort: 53
      protocol: TCP
    - containerPort: 180
      hostPort: 180
    - containerPort: 1443
      hostPort: 1443            
    env:
    - name: TZ
      value: "Europe/Lisbon"
    - name: FTLCONF_webserver_port
      value: '180o,1443os,[::]:180o,[::]:1443os'
    - name: FTLCONF_webserver_api_password
      valueFrom:
        secretKeyRef:
          name: pihole-secrets
          key: FTLCONF_webserver_api_password
    - name: FTLCONF_database_maxDBdays
      value: "30"
    volumeMounts:
    - mountPath: /etc/pihole
      name: data-storage
    - mountPath: /etc/dnsmasq.d
      name: dnsmasq-storage
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: pihole-data-pvc
  - name: dnsmasq-storage
    persistentVolumeClaim:
      claimName: pihole-dnsmasq-pvc