apiVersion: v1
kind: ConfigMap
metadata:
  name: paperlessngx-configmap
data:
  POSTGRES_DB: "paperless"
  POSTGRES_USER: "paperless"
  PAPERLESS_URL: "http://paperless.soafer.duckdns.org"
  PAPERLESS_CSRF_TRUSTED_ORIGINS: "http://paperless.soafer.duckdns.org,http://homeserver01.local:280"

  